force-app/main/default/objects/Country__c/fields/alpha2code__c.field-meta.xml
<CustomField>
    <fullName>alpha2code__c</fullName>
    <label>alpha2code</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3code__c.field-meta.xml
<CustomField>
    <fullName>alpha3code__c</fullName>
    <label>alpha3code</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Capital_city__c.field-meta.xml
<CustomField>
    <fullName>Capital_city__c</fullName>
    <label>Capital city</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/region__c.field-meta.xml
<CustomField>
    <fullName>region__c</fullName>
    <label>region</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CountryTriggerTest.cls
@isTest
public class CountryTriggerTest {
    @isTest
    static void testCountryTriggerUpdateName() {
        Country__c c = new Country__c(Name='OldName', alpha2code__c='ON', alpha3code__c='OLD', Capital_city__c='OldCity', region__c='OldRegion');
        insert c;
        Lead l = new Lead(LastName='Test', Company='Test', Country='OldName');
        insert l;
        c.Name = 'NewName';
        update c;
        Lead updatedLead = [SELECT Country__c FROM Lead WHERE Id = :l.Id];
        System.assertEquals(c.Id, updatedLead.Country__c);
    }
}